version: 0.2

phases:
  install:
   runtime-versions:
      nodejs: 20.x
   commands:
       - npm install -g aws-cdk@2.117.0
       - npm -g install typescript@5.3.3
  pre_build:
   commands:
       - cdk --version  
       - tsc --version
  build:
    commands:
        - node createUser.js  demoman thedemo HelloBernard1
